// angularPrac/angLogicUpdated/app/header/header.component.ts
import { Component, OnInit, Output, EventEmitter} from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnInit {
@Output() selected=new EventEmitter<string>()
  constructor() { }

  ngOnInit(): void {
  }
  onSelect(data: string){
    this.selected.emit(data)
  }

}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Recipe Book</a>
    <button class="navbar-toggler" data-target="#my-nav" data-toggle="collapse" aria-controls="my-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div id="my-nav" class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item " routerLinkActive="active">
                <a class="nav-link" routerLink="/recipes" >Recipe</a>
            </li>
            <li class="nav-item" routerLinkActive="active" [routerLinkActiveOptions]="{exact: true}">
                <a class="nav-link" routerLink="/">Shopping list</a>
            </li>
            <!-- <li class="nav-item">
                <a class="nav-link" href="#" (click)="onSelect('recipe')">Recipe</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#" (click)="onSelect('shopping-list')">Shopping list</a>
            </li> -->
        </ul>
    </div>
</nav>

// reactPrac/ReactPrac/react-logic/src/component/MealRel/Header.js
import Cartitem from "./Cartitem";
export default function Header(props) {
  return (
    <>
      <nav className="navbar navbar-expand-lg navbar-light bg-light">
        <a className="navbar-brand" href="/">
          Navbar
        </a>
        <button
          className="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="/navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span className="navbar-toggler-icon"></span>
        </button>

        <div className="collapse navbar-collapse" id="navbarSupportedContent">
          <ul className="navbar-nav ml-auto">
            <Cartitem onOpen={props.onOpen} />
          </ul>
        </div>
      </nav>
    </>
  );
}
